import { useEffect, useState } from "react";
import { ArrowLeft, Printer } from "lucide-react";
import { Button } from "../components/Button";
import { getNoteById } from "../data/noteRepository";
import type { SavedNote } from "../types/note";
import { formatDateTime } from "../utils/format";
import { navigate } from "../App";

function PrintList({ title, items }: { title: string; items: string[] }) {
  return (
    <section className="print-section">
      <h2>{title}</h2>
      <ul>
        {items.map((item) => <li key={item}>{item}</li>)}
      </ul>
    </section>
  );
}

export function PrintView({ id }: { id: string }) {
  const [note, setNote] = useState<SavedNote | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    getNoteById(id)
      .then(setNote)
      .catch((err) => setError(err instanceof Error ? err.message : "Could not load print view."));
  }, [id]);

  if (error) {
    return <p className="error-line">{error}</p>;
  }

  if (!note) {
    return <p className="helper-line">Loading print view...</p>;
  }

  return (
    <div className="print-page-shell">
      <div className="print-toolbar">
        <Button icon={<ArrowLeft size={16} />} onClick={() => navigate(`/notes/${note.id}`)}>Back to Detail</Button>
        <Button variant="primary" icon={<Printer size={16} />} onClick={() => window.print()}>Print / Save as PDF</Button>
      </div>

      <article className="print-document">
        <header className="print-header">
          <p>Note Summeraizer</p>
          <h1>{note.title}</h1>
          <span>Generated by noteS in Note Summeraizer</span>
        </header>

        <section className="print-metadata">
          <div><strong>Created</strong><span>{formatDateTime(note.createdAt)}</span></div>
          <div><strong>Source type</strong><span>{note.sourceType}</span></div>
          <div><strong>Audience</strong><span>{note.audience}</span></div>
          <div><strong>Summary type</strong><span>{note.summaryType}</span></div>
          <div><strong>Customer/account</strong><span>{note.customerName || "Not provided"}</span></div>
          <div><strong>Ticket ID</strong><span>{note.ticketId || "Not provided"}</span></div>
          <div><strong>Product/system</strong><span>{note.productSystem || "Not provided"}</span></div>
          <div><strong>Priority</strong><span>{note.priority || "Not provided"}</span></div>
        </section>

        <section className="print-section">
          <h2>Summary</h2>
          <p>{note.generatedSummary}</p>
        </section>

        <PrintList title="Action Items" items={note.actionItems} />
        <PrintList title="Next Steps" items={note.nextSteps} />
        <PrintList title="Open Questions" items={note.openQuestions} />

        <section className="print-section">
          <h2>Tags</h2>
          <p>{note.tags.join(", ") || "No tags"}</p>
        </section>

        <footer className="print-footer">Generated by noteS in Note Summeraizer</footer>
      </article>
    </div>
  );
}
