import { AlertTriangle, CheckCircle2, Copy, ListChecks, MessageSquareText } from "lucide-react";
import { Button } from "./Button";
import type { NoteSummaryOutput } from "../types/note";

interface NotePreviewProps {
  output: NoteSummaryOutput;
  onCopy?: () => void;
}

function ListBlock({ title, items }: { title: string; items: string[] }) {
  return (
    <div className="summary-list-block">
      <h3>{title}</h3>
      <ul>
        {items.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
    </div>
  );
}

export function NotePreview({ output, onCopy }: NotePreviewProps) {
  return (
    <div className="note-preview">
      <div className="note-preview-header">
        <div>
          <p className="eyebrow">Generated by noteS</p>
          <h2>{output.title}</h2>
        </div>
        {onCopy ? <Button icon={<Copy size={16} />} onClick={onCopy}>Copy Summary</Button> : null}
      </div>

      {output.sensitiveInfoDetected ? (
        <div className="warning-banner">
          <AlertTriangle size={18} />
          <span>{output.sensitiveInfoWarning}</span>
        </div>
      ) : null}

      <div className="summary-section">
        <h3><MessageSquareText size={18} /> Summary</h3>
        <p>{output.summary}</p>
      </div>

      <div className="summary-grid">
        <ListBlock title="Action Items" items={output.actionItems} />
        <ListBlock title="Open Questions" items={output.openQuestions} />
        <ListBlock title="Next Steps" items={output.nextSteps} />
      </div>

      <div className="tag-row">
        {output.tags.map((tag) => (
          <span className="tag" key={tag}>
            <CheckCircle2 size={14} />
            {tag}
          </span>
        ))}
      </div>
    </div>
  );
}
